### ISSUE TITLE
Allow for Library names containing "/"

### ISSUE THREAD

**Issue by BEisem** [InsertDisc/pattrmm#23]
When I try to add a Plex library that contains a "/" in the name, PATTRMM is unable to create the json file because Linux does not allow that character in filenames. I get the following error:

```
Waiting for next run at 04:21 PM
Verifying files.
Data folder present...
Logs folder present...
Preference folder present...
Settings file present.
PMM config file found.
Checking folder structure for Reality / Talk / Documentary TV.
Checking Reality / Talk / Documentary TV files...
Creating Reality / Talk / Documentary TV keys file..
Traceback (most recent call last):
  File "//main.py", line 28, in <module>
    exec(f.read())
  File "<string>", line 581, in <module>
FileNotFoundError: [Errno 2] No such file or directory: './data/Reality-/-Talk-/-Documentary-TV-keys.json'
```

**Comment by InsertDisc** [comment]
These types of library names will now be handled accordingly.
