### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by Scridgeon** [InsertDisc/pattrmm#60]
I installed pattrmm in unraid and am receiving an error when manually running.
I'm using this docker command to initialize pattrmm:

docker run --rm -it -v "/mnt/user/appdata/pattrmm/preferences:/preferences" -v "/mnt/user/appdata/Kometa/config:/config" ghcr.io/insertdisc/pattrmm --run

pattrmm finds all of my shows but appears to be failing when sorting them. Below is the last few lines from the log.

```
TV Shows Keys updated...
TV Shows TMDB data updated...
Writing TV Shows Overlay Template to Returning Soon TV Shows overlay file.
TV Shows template applied.
Generating TV Shows overlay body.
TV Shows overlay body generated. Writing to file.
Overlay body appended to TV Shows-returning-soon-overlay.
Reading TV Shows cache file...
Filtering TV Shows data...
Sorting TV Shows...
Traceback (most recent call last):
  File "//main.py", line 11, in <module>
    exec(f.read())
  File "<string>", line 2248, in <module>
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by Scridgeon** [comment]
This is the error that I receive when pattrmm runs via the cron.

```
Traceback (most recent call last):
  File "//main.py", line 28, in <module>
    exec(f.read())
  File "<string>", line 1691, in <module>
  File "<string>", line 1533, in dict_to_json
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.10/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/local/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ConnectionError is not JSON serializable
Searching... (82/148) Found ID ==> 15621 for "The Newsroom"
Searching... (83/148) Found ID ==> 92830 for "Obi-Wan Kenobi"
Searching... (84/148) Found ID ==> 111800 for "The Old Man"
```

**Comment by InsertDisc** [comment]
Are you still experiencing this issue?

**Comment by Scridgeon** [comment]
I gave up trying to get pattrmm to work and moved to Kometa. Thank you for following up.

**Comment by InsertDisc** [comment]
PATTRMM doesn't with without Kometa.
