### ISSUE TITLE
UnboundLocalError: local variable 'library_type' referenced before assignment

### ISSUE THREAD

**Issue by joca879** [InsertDisc/pattrmm#64]
I've tried running pattrmm in docker in a synology NAS and I'm having this error in the container log:

"Waiting for next run at 05:09 PM
Verifying files...
Data folder present...
Stats folder present...
Logs folder present...
Preferences folder present...
Settings file present.
Vars module file present.
PMM config file found.
Movies is not compatible with the 'Returning Soon' method. Skipping.
Traceback (most recent call last):
  File "//main.py", line 28, in <module>
    exec(f.read())
  File "<string>", line 1302, in <module>
  File "/vars.py", line 298, in type
    return library_type
UnboundLocalError: local variable 'library_type' referenced before assignment"

Can someone help?

**Comment by InsertDisc** [comment]
Head over to our discord server. It will be quicker to help you there.

**Comment by InsertDisc** [comment]
If not, double check the library names in your pattrmm settings yml match watch you have in Plex.
